title: Divya Thomas # your name (or website title) here
logo: "images/profpic_cropped.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  M.S. Computer Science - Boston University 
  <br>
  B.S. Bioinformatics - University of Iowa
  <hr>
  <a href="https://www.linkedin.com/in/divyaalicethomas/">View My LinkedIn Profile</a>  
  
theme: jekyll-theme-minimal
google_analytics: G-PPKR1KG6JC # your Google Analytics tracking ID here
